DROP TABLE IF EXISTS account_cve_cache;
DROP TABLE IF EXISTS cluster_cve_cache;
DROP TABLE IF EXISTS cluster_image;
DROP TABLE IF EXISTS image_cve;
DROP TABLE IF EXISTS cve;
DROP TABLE IF EXISTS image;
DROP TABLE IF EXISTS cluster;
DROP TABLE IF EXISTS account;

DROP TYPE IF EXISTS severity;
DROP FUNCTION IF EXISTS empty;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM manager;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM cve_aggregator;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM vmaas_gatherer;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM pyxis_gatherer;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM archive_db_writer;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM manager;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM cve_aggregator;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM vmaas_gatherer;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM pyxis_gatherer;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM archive_db_writer;

DROP USER IF EXISTS manager;
DROP USER IF EXISTS cve_aggregator;
DROP USER IF EXISTS vmaas_gatherer;
DROP USER IF EXISTS pyxis_gatherer;
DROP USER IF EXISTS archive_db_writer;
