# options for analysis running
run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m

linters-settings:
  gocyclo:
    min-complexity: 40

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - govet
    - ineffassign
    - typecheck
    - varcheck
    - goimports
    - revive
    - gocyclo

