version: "2"
linters:
  default: none
  enable:
    - copyloopvar
    - errcheck
    - gocyclo
    - govet
    - ineffassign
    - revive
    - unused
  settings:
    gocyclo:
      min-complexity: 40
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - linters:
        - revive
        path: "base/utils/*"
        text: "var-naming: avoid meaningless package names"
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
