{
 "title": "vuln4shift-backend",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "datasource_rds", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "ocp-vulnerability-stage,ocp-vulnerability-prod"
   }
  ]
 },
 "panels": [
  { "title": "SLO reports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_time_count{exported_service=\"ocp-vulnerability\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Error rate downtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "hours" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(1 - avg_over_time(service:sli:status_5xx:pctl5rate5m{exported_service=\"ocp-vulnerability\"}[$__range])) * 720"
    }
   ]
  },
  {
   "title": "Latency downtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "hours" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(1 - avg_over_time(service:sli:latency_gt_2000:pctl10rate5m{exported_service=\"ocp-vulnerability\"}[$__range])) * 720"
    }
   ]
  },
  {
   "title": "Error rate uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(service:sli:status_5xx:pctl5rate5m{exported_service=\"ocp-vulnerability\"}[$__range])"
    }
   ]
  },
  {
   "title": "Latency uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(service:sli:latency_gt_2000:pctl10rate5m{exported_service=\"ocp-vulnerability\"}[$__range])"
    }
   ]
  },
  {
   "title": "Latency uptime (30d)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(service:sli:latency_gt_2000:pctl10rate5m{exported_service=\"ocp-vulnerability\"}[30d])"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "digest writer restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{container=\"vuln4shift-backend-digest-writer\"}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "vmaas sync restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{container=\"vuln4shift-backend-vmaas-sync\"}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "pyxis gatherer restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{container=\"vuln4shift-backend-pyxis-gatherer\"}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "manager restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{container=\"vuln4shift-backend-manager\"}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "digest writer processing errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(vuln4shift_digestwriter_parse_incoming_messages_error[$__range])) + sum(increase(vuln4shift_digestwriter_stored_messages_error[$__range])) + sum(increase(vuln4shift_kafka_consuming_errors[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Kafka consumer lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_kafka_sum_offset_lag_sum{consumer_group=~\"sha_extractor_app|vuln4shift_digest_writer_app\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "RDS storage usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rdsosmetrics_fileSys_usedPercent{exported_instance=~\"ocp-vulnerability-.*\"}) by (mount_point)",
     "legendFormat": "{{mount_point}}",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "RDS CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(label_replace(rdsosmetrics_processList_cpuUsedPc{exported_instance=~\"ocp-vulnerability-.*\", name=~\"postgres:.*\"}, \"db_user\", \"$1\", \"name\", \"postgres: ([^ ]+) .+\")) by (db_user)",
     "legendFormat": "{{db_user}}"
    }
   ]
  },
  {
   "title": "digest writer processing rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(vuln4shift_kafka_consumed_messages[5m]))",
     "legendFormat": "messages"
    }
   ]
  },
  {
   "title": "Manager API Latency - 3scale",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_time_bucket{exported_service=\"ocp-vulnerability\"}[$__rate_interval])) by (le)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "SHA-Extractor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Stats Watcher (Counters)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(ccx_consumer_received_total{namespace=\"$namespace\", service=\"sha-extractor-instance\"}[1m]))",
     "legendFormat": "received"
    },
    {
     "expr": "sum(increase(ccx_downloaded_total_count{namespace=\"$namespace\", service=\"sha-extractor-instance\"}[1m]))",
     "legendFormat": "downloaded"
    },
    {
     "expr": "sum(increase(ccx_engine_processed_total{namespace=\"$namespace\", service=\"sha-extractor-instance\"}[1m]))",
     "legendFormat": "processed"
    },
    {
     "expr": "sum(increase(ccx_published_total{namespace=\"$namespace\", service=\"sha-extractor-instance\"}[1m]))",
     "legendFormat": "published"
    },
    {
     "expr": "sum(increase(ccx_failures_total{namespace=\"$namespace\", service=\"sha-extractor-instance\"}[1m]))",
     "legendFormat": "failures"
    },
    {
     "expr": "sum(increase(ccx_not_handled_total{namespace=\"$namespace\", service=\"sha-extractor-instance\"}[1m]))",
     "legendFormat": "not handled"
    },
    {
     "expr": "sum(increase(ccx_engine_processed_timeout_total{namespace=\"$namespace\", service=\"sha-extractor-instance\"}[1m]))",
     "legendFormat": "engine timeouts"
    }
   ]
  },
  {
   "title": "Pods CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"sha-extractor-.*\"}[1m])) by (pod)"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"sha-extractor-.*\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Pods network in",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"sha-extractor-.*\"}[1m])) by (pod)"
    }
   ]
  },
  {
   "title": "Pods network out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"sha-extractor-.*\"}[1m])) by (pod)"
    }
   ]
  },
  {
   "title": "Stats Watcher: Seconds to Process a Single Archive",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"0.1\"})",
     "legendFormat": "( -Inf; 0.1 >"
    },
    {
     "expr": "sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"0.25\"}) - ignoring(le) sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"0.1\"})",
     "legendFormat": "( 0.1; 0.25 >"
    },
    {
     "expr": "sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"0.5\"}) - ignoring(le) sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"0.25\"})",
     "legendFormat": "( 0.25; 0.5 >"
    },
    {
     "expr": "sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"0.75\"}) - ignoring(le) sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"0.5\"})",
     "legendFormat": "( 0.5; 0.75 >"
    },
    {
     "expr": "sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"1.0\"}) - ignoring(le) sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"0.75\"})",
     "legendFormat": "( 0.75; 1.0 >"
    },
    {
     "expr": "sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"10.0\"}) - ignoring(le) sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"1.0\"})",
     "legendFormat": "( 1.0; 10.0 >"
    },
    {
     "expr": "sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"+Inf\"}) - ignoring(le) sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"10.0\"})",
     "legendFormat": "( 10.0; +Inf )"
    }
   ]
  },
  {
   "title": "Stats Watcher: Seconds to Download a Single Archive",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"0.1\"})",
     "legendFormat": "( -Inf; 0.1 >"
    },
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\",le=\"0.25\"}) - ignoring(le) sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"0.1\"})",
     "legendFormat": "( 0.1; 0.25 >"
    },
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"0.5\"}) - ignoring(le) sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"0.25\"})",
     "legendFormat": "( 0.25; 0.5 >"
    },
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"0.75\"}) - ignoring(le) sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\",service=\"sha-extractor-instance\",  le=\"0.5\"})",
     "legendFormat": "( 0.5; 0.75 >"
    },
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"1.0\"}) - ignoring(le) sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\",le=\"0.75\"})",
     "legendFormat": "( 0.75; 1.0 >"
    },
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"10.0\"}) - ignoring(le) sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\",le=\"1.0\"})",
     "legendFormat": "( 1.0; 10.0 >"
    },
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"+Inf\"}) - ignoring(le) sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"10.0\"})",
     "legendFormat": "( 10.0; +Inf )"
    }
   ]
  },
  {
   "title": "Stats Watcher: Seconds to Publish a Single Archive",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"0.005\"})",
     "legendFormat": "( -Inf; 0.005 >"
    },
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"0.01\"}) - ignoring(le) sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"0.005\"})",
     "legendFormat": "( 0.005; 0.01 >"
    },
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\",  le=\"0.025\"}) - ignoring(le) sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"0.01\"})",
     "legendFormat": "( 0.01; 0.025 >"
    },
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"0.1\"}) - ignoring(le) sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\",  le=\"0.025\"})",
     "legendFormat": "( 0.025; 0.1 >"
    },
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"0.5\"}) - ignoring(le) sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"0.1\"})",
     "legendFormat": "( 0.1; 0.5 >"
    },
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"10.0\"}) - ignoring(le) sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"0.5\"})",
     "legendFormat": "( 0.5; 10.0 >"
    },
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"+Inf\"}) - ignoring(le) sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", service=\"sha-extractor-instance\", le=\"10.0\"})",
     "legendFormat": "( 10.0; +Inf )"
    }
   ]
  }
 ]
}