name: Run unit tests

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build unit test image
        run: docker-compose build vuln4shift_unit_tests

      - name: Run unit tests
        run: docker-compose run vuln4shift_unit_tests

      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          files: ./coverage.txt
          flags: unittests
          name: codecov-umbrella
          verbose: true

      - name: Cleanup
        run: docker-compose down
