name: Run unit tests

on:
  push:
    braches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build unit test image
        run: docker-compose build vuln4shift_unit_tests

      - name: Run unit tests
        run: docker-compose run --rm vuln4shift_unit_tests

      - name: Cleanup
        run: docker-compose down
